version: '3'
services:

  postgres:
    container_name: "postgres"
    image: "postgres:14"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    ports:
      - "5432:5432" # do not use in production
    volumes:
      - "$PWD/var/lib/postgresql/data:/var/lib/postgresql/data"
