version: '3'
services:

  openai-bot:
    container_name: "openai-bot"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "OPENAI_API_KEY=${OPENAI_API_KEY}"
      - "OPENAI_ORG_ID=${OPENAI_ORG_ID}"
      - "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}"
      - "POSTGRES_DSN=${POSTGRES_DSN}"
    depends_on:
      - postgres

  postgres:
    container_name: "postgres"
    image: "postgres:14"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    volumes:
      - "$PWD/var/lib/postgresql/data:/var/lib/postgresql/data"
