name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Run tests
        run: make test

      - name: Run linters and check formatting
        run: |
          go get -u golang.org/x/lint/golint
          go get -u github.com/go-toolsmith/astequal
          go get -u github.com/go-toolsmith/strparse
          go get -u golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
          make fmt vet
